# Generated by Django 6.0.6 on 2026-07-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('tender_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('emd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tender_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('published_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
