# Generated by Django 6.0.6 on 2026-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_organization_alter_tender_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='action_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='notice_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='source',
            field=models.CharField(default='AP eProcurement', max_length=50),
        ),
    ]
