# Generated by Django 6.0.6 on 2026-07-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tender_action_html_tender_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW', 'New Tender'), ('UPDATED', 'Tender Updated'), ('CORRIGENDUM', 'Corrigendum'), ('CLOSING_TODAY', 'Closing Today'), ('CLOSING_TOMORROW', 'Closing Tomorrow')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
