# Generated by Django 6.0.6 on 2026-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tendernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.TextField(),
        ),
    ]
