# Generated by Django 6.0.6 on 2026-06-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
