# Generated by Django 6.0.6 on 2026-06-19 21:54

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_department_groupphotoupload_worksite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphotoupload',
            name='work_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.worksite'),
        ),
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksite',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='groupphotoupload',
            name='group_photo',
            field=models.ImageField(upload_to=attendance.models.group_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='unknownperson',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
