# Generated by Django 6.0.6 on 2026-06-23 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_groupphotoupload_work_site_worker_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField()),
                ('work_description', models.TextField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.site')),
            ],
        ),
    ]
