# Generated by Django 6.0.6 on 2026-06-24 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_offlineattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerFaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='worker_learned_faces/')),
                ('face_encoding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learned_from_unknown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.unknownperson')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.worker')),
            ],
        ),
    ]
