# Generated by Django 6.0.6 on 2026-06-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_workerfaceencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
    ]
