# Generated by Django 6.0.6 on 2026-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_worker_face_embedding_worker_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerfaceencoding',
            old_name='face_encoding',
            new_name='face_embedding',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='face_encoding',
        ),
        migrations.AlterField(
            model_name='worker',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
    ]
